apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: sv-go-test-repo
          artifact-id: 4271e62b-efce-45c2-9d06-d85c81e84da9
          target-environment: QA-Env